twitter = "@zxkane"
largeTwitterCard = false # set to true if you want to show a large twitter card image. The default is a small twitter card image
introDescription = "A tech blog sharing personal experiences and insights about cloud computing, software development, and emerging technologies."
introURL = "about/" # set the url for the 'read more' button below the introDescription, or set to false to not show the button
description = "A tech blog sharing personal experiences and insights about cloud computing, software development, and emerging technologies." # set your site's description here. will be use for home page content meta tags (seo). Alternatively set this description in your homepage content file i.e content/_index.md. Whatever is set in the latter will take precedence

# showShare = false # Uncomment to not show share buttons on each post. Also available in each post's front matter.

# Google analytics Id
ga_analytics = "UA-11561366-2"

# Baidu analytics Id
# baidu_analytics = "XXXXXXXX"

# limit the number of taxonomies links shown on the sidebar of each page by default.
numberOfTagsShown = 14 # Applies for all other default & custom taxonomies. e.g categories, brands see https://gohugo.io/content-management/taxonomies#what-is-a-taxonomy

# will be used on share >> twitter, facebook, linkedin
fallBackOgImage = "images/thumbnail.png"

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 7

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = false

# enable math notation. Switch to `true` to enable mathjax in your site.
enableMathNotation = false

# directory(s) where your articles are located
mainSections = ["posts"] # see config details here https://gohugo.io/functions/where/#mainsections

# center logo on navbar
centerLogo = true # Set to "true" for centering or "false" for left aligned.

footerLogo = "img/portrait.jpg"

# Label Non inline images on an article body
figurePositionShow = false # toggle on or off globally
# you can toggle this behaviour on or off on per page using the same variable inside your articles frontmatter
figurePositionLabel = "Figure" # the text before image number e.g Figure 1.0

# Set the collapsed mobile navigation to either appear from the left or the right
mobileNavigation = "left" # if you prefer right change to 'right'

# some site owners want to decide how they would like their sites to be introduced users. These settings give you as a site owner to decide how the user will view your site for the first time.

# please note that you cannot enforce both modes at the same time. i.e by enforcing one mode, you priotise it over the other (by setting it to true). enforceDarkMode will be commented out

# please also not that mode toggle UI will remain in place. That way, if a user prefers darkmode, they can have their way.

enforceLightMode = false
# enforceDarkMode = false

# customize footer icon. see issue https://github.com/chipzoller/hugo-clarity/issues/77
# footerLogo = "icons/copy.svg"

# Text for the languages menu.
languageMenuName = "ðŸŒ"

# Title separator, default to |.
# titleSeparator = "|"

# Enable or disable comments globally. Default to true.
# comments = false

# Maximum number of recent posts.
numberOfRecentPosts = 8

# Maximum number of featured posts.
pinFeatured = true
numberOfFeaturedPosts = 8

# Date format. Checkout https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for details.
# dateFormat = "2006-01-02" # Default to "Jan 2, 2006".
# customFonts = false # toggle to true if you want to use custom fonts only.

# The year when ths website was created, this value is used in the copyright
# notice of the footer.
since = 2006

# tell hugo where you store your icons e.g favicons. This is useful if you're using an apache server and there are conflicts >> see issue https://github.com/chipzoller/hugo-clarity/issues/74. If this is applicable to you, be sure to copy the contents of https://github.com/chipzoller/hugo-clarity/tree/master/static/icons to your preferred icons directory 
iconsDir = "icons/" # without a leading forward slash

rss_summary = true
rss_summary_read_more_link = true

enableSearch = true

# website author
[author]
name = "Kane Zhu"
photo = "/img/favicon.ico" #include this if you would like to show the author photo on the sidebar

[adsense]
publisher = "ca-pub-9948807638905550"

[cloudwatch_rum]
enable = true

[aws_clickstream]
enable = true
app_id = "blog"
endpoint = "https://kane.clickstream.aws.kane.mx/collect"

[plausible_analytics]
enable = false # to enable plausible analytics set to true.
websiteDomain = "example.com" # domain name of your website, most cases same as your base url
# plausibleDomain = "plausible.io" # default is set to plausible.io, only required if plausible is selfhosted
# scritpName = "plausible" # default is set to plausible, only required if using a custome name for script

[markdownExport]
# Enable/disable "Copy as Markdown" button globally
enable = true
# Include front matter metadata in markdown export
includeFrontMatter = true
# Add source attribution link in exported markdown
includeAttribution = true
# Use reference-style links for cleaner markdown
useReferenceLinks = true
# Format style: "llm" (optimized for LLMs), "github", "plain"
formatStyle = "llm"

[github]
# GitHub repository for source markdown files
repo = "zxkane/articles"
branch = "master"
contentPath = "content"